// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticlePreview: typeof import('./components/article-preview/index.vue')['default']
    ArticlePreviewMain: typeof import('./components/article-preview-main/index.vue')['default']
    CommentInput: typeof import('./components/h-comment/components/comment-input.vue')['default']
    HButton: typeof import('./components/h-button/index.vue')['default']
    HCard: typeof import('./components/h-card/index.vue')['default']
    HComment: typeof import('./components/h-comment/index.vue')['default']
    HDialog: typeof import('./components/h-dialog/index.vue')['default']
    HMessage: typeof import('./components/h-message/index.vue')['default']
    HMessageBox: typeof import('./components/h-message-box/index.vue')['default']
    HPagination: typeof import('./components/h-pagination/index.vue')['default']
    HTag: typeof import('./components/h-tag/index.vue')['default']
    NavBreadcrumb: typeof import('./components/nav-breadcrumb/index.vue')['default']
    ProfileCard: typeof import('./components/profile-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalkItem: typeof import('./components/talk-item/index.vue')['default']
    ThemeToggler: typeof import('./components/theme-toggler/index.vue')['default']
  }
}
